import { createAvatarRuntime } from "../../avatars/runtime.mjs";
import { getRunnerSessionStats } from "../runner-session-state.mjs";

export function createRunnerAvatarRuntime({
  cwd,
  stateRoot,
  provider,
  modelId,
  modelRegistry,
  settingsManager,
  authStorage,
  createAgentSession,
  engine,
  sessionBinding,
  getRuntimeHost,
  getCurrentUserRequest,
  getCurrentModel,
  namespace,
  shellRuntime,
  lspService,
  webTools,
  hostedTools,
  modelContextDumper,
  onModelPayload,
  logger,
}) {
  return createAvatarRuntime({
    cwd,
    stateRoot,
    provider,
    modelId,
    modelRegistry,
    settingsManager,
    authStorage,
    createAgentSession,
    getParentEngine: () => engine,
    getParentSessionId: () => getRunnerSessionStats(sessionBinding.get(), getRuntimeHost?.()).sessionId ?? null,
    getCurrentUserRequest,
    getCurrentModel,
    namespace,
    shellRuntime,
    lspService,
    webTools,
    hostedTools,
    modelContextDumper,
    onModelPayload,
    logger,
  });
}
