import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { resolveStaticPath } from "../src/web-ui/server.mjs";

export async function runWebUiSmoke({ cwd = process.cwd() } = {}) {
  console.log("--- smoke: web UI prototype ---");
  const root = join(cwd, "src", "web-ui");
  const shell = readFileSync(join(root, "src", "components", "AppShell.tsx"), "utf8");
  const explorer = readFileSync(join(root, "src", "components", "FileExplorer.tsx"), "utf8");
  const treeAdapter = readFileSync(join(root, "src", "fileTreeAdapter.ts"), "utf8");
  const timeline = readFileSync(join(root, "src", "components", "SessionTimeline.tsx"), "utf8");
  const timelineList = readFileSync(join(root, "src", "components", "timeline", "TimelineList.tsx"), "utf8");
  const timelineBlocks = readFileSync(join(root, "src", "components", "timeline", "TimelineBlocks.tsx"), "utf8");
  const timelineAdapter = readFileSync(join(root, "src", "timelineAdapter.ts"), "utf8");
  const right = readFileSync(join(root, "src", "components", "RightSidebar.tsx"), "utf8");
  const composer = readFileSync(join(root, "src", "components", "Composer.tsx"), "utf8");
  const model = readFileSync(join(root, "src", "model.ts"), "utf8");
  const css = readFileSync(join(root, "src", "styles", "shell.css"), "utf8");
  const tokens = readFileSync(join(root, "src", "styles", "tokens.css"), "utf8");
  const pkg = readFileSync(join(cwd, "package.json"), "utf8");

  assert.match(pkg, /"web:dev": "vite --config src\/web-ui\/vite\.config\.mjs"/);
  assert.match(pkg, /"web:build": "tsc -p src\/web-ui\/tsconfig\.json/);
  assert.match(pkg, /"@pierre\/trees":/);
  assert.match(shell, /<FileExplorer root=\{model\.workspace\}/);
  assert.match(shell, /<SessionTimeline timeline=\{model\.timeline\}/);
  assert.match(shell, /<RightSidebar sessions=\{model\.sessions\} activity=\{model\.activity\}/);
  assert.match(model, /export type WebUiModel/);
  assert.match(model, /MarchTimelineEvent/);
  assert.match(model, /TimelineItem/);
  assert.match(model, /ActivityEvent/);
  assert.match(explorer, /@pierre\/trees\/react/);
  assert.match(explorer, /aria-label="Projects"/);
  assert.match(explorer, /className="projects-header"/);
  assert.match(explorer, /className="project-tree-host"/);
  assert.match(treeAdapter, /createProjectFileTreeInput/);
  assert.match(treeAdapter, /GitStatusEntry/);
  assert.match(timeline, /normalizeTimelineEvents/);
  assert.match(timeline, /<TimelineList items=\{items\}/);
  assert.match(timelineList, /aria-label="Session events"/);
  assert.match(timelineBlocks, /className="timeline-aux tool-block"/);
  assert.match(timelineBlocks, /permission-block/);
  assert.match(timelineAdapter, /tool_result/);
  assert.match(right, /className="right-header">会话/);
  assert.match(right, /right-divider">Activity/);
  assert.doesNotMatch(right, /todo|Todos/i);
  assert.match(composer, /className="composer-box"/);
  assert.match(css, /grid-template-areas: "sidebar main right" "sidebar footer right"/);
  assert.match(css, /height: var\(--header-height\)/);
  assert.match(css, /border-right: 1px solid var\(--color-border-subtle\)/);
  assert.match(css, /--trees-selected-bg-override: var\(--color-accent-soft\)/);
  assert.match(css, /\.timeline-aux/);
  assert.match(css, /\.terminal-block pre/);
  assert.match(css, /max-width: 920px/);
  assert.match(css, /data-left-open="true"/);
  assert.match(tokens, /@layer theme\.palette, theme\.semantic, theme\.component, base/);
  assert.match(tokens, /--palette-blue-600:/);
  assert.match(tokens, /--color-bg-surface:/);
  assert.match(tokens, /--shell-left-width:/);
  assert.doesNotMatch(tokens, /--bg:|--line:|--accent:/);
  assert.match(tokens, /--font-sans:/);
  assert.match(tokens, /"Segoe UI Variable Text"/);
  assert.match(tokens, /DengXian/);
  assert.match(tokens, /"等线"/);
  assert.match(tokens, /DengXian[\s\S]*"Microsoft YaHei UI"/);
  assert.doesNotMatch(tokens, /PingFang SC|Noto Sans CJK|Source Han Sans|微软雅黑/i);
  assert.doesNotMatch(css, /todo/i);
  assert.equal(resolveStaticPath(root, "/..%2fpackage.json"), null);
  assert.ok(resolveStaticPath(root, "/")?.endsWith(join("web-ui", "index.html")));
  console.log("  PASS");
}
