import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { resolveStaticPath } from "../src/web-ui/server.mjs";

export async function runWebUiSmoke({ cwd = process.cwd() } = {}) {
  console.log("--- smoke: web UI prototype ---");
  const root = join(cwd, "src", "web-ui");
  const shell = readFileSync(join(root, "src", "components", "AppShell.tsx"), "utf8");
  const explorer = readFileSync(join(root, "src", "components", "FileExplorer.tsx"), "utf8");
  const timeline = readFileSync(join(root, "src", "components", "SessionTimeline.tsx"), "utf8");
  const right = readFileSync(join(root, "src", "components", "RightSidebar.tsx"), "utf8");
  const composer = readFileSync(join(root, "src", "components", "Composer.tsx"), "utf8");
  const model = readFileSync(join(root, "src", "model.ts"), "utf8");
  const css = readFileSync(join(root, "src", "styles", "shell.css"), "utf8");
  const tokens = readFileSync(join(root, "src", "styles", "tokens.css"), "utf8");
  const pkg = readFileSync(join(cwd, "package.json"), "utf8");

  assert.match(pkg, /"web:dev": "vite --config src\/web-ui\/vite\.config\.mjs"/);
  assert.match(pkg, /"web:build": "tsc -p src\/web-ui\/tsconfig\.json/);
  assert.match(shell, /<FileExplorer root=\{model\.workspace\}/);
  assert.match(shell, /<SessionTimeline timeline=\{model\.timeline\}/);
  assert.match(shell, /<RightSidebar sessions=\{model\.sessions\} activity=\{model\.activity\}/);
  assert.match(model, /export type WebUiModel/);
  assert.match(model, /TimelineEvent/);
  assert.match(model, /ActivityEvent/);
  assert.match(explorer, /aria-label="Projects"/);
  assert.match(explorer, /className="projects-header"/);
  assert.match(explorer, /className="project-tree"/);
  assert.match(timeline, /className="timeline"/);
  assert.match(timeline, /className="tool-row"/);
  assert.match(right, /className="right-header">会话/);
  assert.match(right, /right-divider">Activity/);
  assert.doesNotMatch(right, /todo|Todos/i);
  assert.match(composer, /className="composer-box"/);
  assert.match(css, /grid-template-areas: "sidebar main right" "sidebar footer right"/);
  assert.match(css, /height: var\(--header-height\)/);
  assert.match(css, /border-right: 1px solid var\(--color-border-subtle\)/);
  assert.match(css, /max-width: 920px/);
  assert.match(css, /data-left-open="true"/);
  assert.match(tokens, /@layer theme\.palette, theme\.semantic, theme\.component, base/);
  assert.match(tokens, /--palette-blue-600:/);
  assert.match(tokens, /--color-bg-surface:/);
  assert.match(tokens, /--shell-left-width:/);
  assert.doesNotMatch(tokens, /--bg:|--line:|--accent:/);
  assert.match(tokens, /--font-sans:/);
  assert.doesNotMatch(tokens, /Microsoft YaHei|微软雅黑/i);
  assert.doesNotMatch(css, /todo/i);
  assert.equal(resolveStaticPath(root, "/..%2fpackage.json"), null);
  assert.ok(resolveStaticPath(root, "/")?.endsWith(join("web-ui", "index.html")));
  console.log("  PASS");
}
