import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { resolveStaticPath } from "../src/web-ui/server.mjs";

export async function runWebUiSmoke({ cwd = process.cwd() } = {}) {
  console.log("--- smoke: web UI prototype ---");
  const root = join(cwd, "src", "web-ui");
  const app = readFileSync(join(root, "src", "App.tsx"), "utf8");
  const shell = readFileSync(join(root, "src", "components", "AppShell.tsx"), "utf8");
  const explorer = readFileSync(join(root, "src", "components", "FileExplorer.tsx"), "utf8");
  const treeAdapter = readFileSync(join(root, "src", "fileTreeAdapter.ts"), "utf8");
  const timeline = readFileSync(join(root, "src", "components", "SessionTimeline.tsx"), "utf8");
  const timelineList = readFileSync(join(root, "src", "components", "timeline", "TimelineList.tsx"), "utf8");
  const timelineBlocks = readFileSync(join(root, "src", "components", "timeline", "TimelineBlocks.tsx"), "utf8");
  const timelineAdapter = readFileSync(join(root, "src", "timelineAdapter.ts"), "utf8");
  const right = readFileSync(join(root, "src", "components", "RightSidebar.tsx"), "utf8");
  const composer = readFileSync(join(root, "src", "components", "Composer.tsx"), "utf8");
  const model = readFileSync(join(root, "src", "model.ts"), "utf8");
  const runtimeClient = readFileSync(join(root, "src", "runtime", "client.ts"), "utf8");
  const runtimeHook = readFileSync(join(root, "src", "runtime", "useWebRuntime.ts"), "utf8");
  const runtimeTimeline = readFileSync(join(root, "src", "runtime", "runtimeTimeline.ts"), "utf8");
  const css = readFileSync(join(root, "src", "styles", "shell.css"), "utf8");
  const tokens = readFileSync(join(root, "src", "styles", "tokens.css"), "utf8");
  const pkg = readFileSync(join(cwd, "package.json"), "utf8");
  const args = readFileSync(join(cwd, "src", "cli", "args.mjs"), "utf8");
  const configuredCommand = readFileSync(join(cwd, "src", "cli", "startup", "configured-command.mjs"), "utf8");
  const server = readFileSync(join(root, "server.mjs"), "utf8");
  const webCommand = readFileSync(join(root, "command.mjs"), "utf8");
  const runtimeHost = readFileSync(join(root, "runtime-host.mjs"), "utf8");
  const sessionManager = readFileSync(join(root, "session-manager.mjs"), "utf8");

  assert.match(pkg, /"web:dev": "node bin\/march\.mjs web --dev"/);
  assert.match(pkg, /"web:build": "tsc -p src\/web-ui\/tsconfig\.json/);
  assert.match(pkg, /"@pierre\/trees":/);
  assert.match(args, /"web"/);
  assert.match(args, /workspace: \{ type: "string" \}/);
  assert.match(args, /dev: \{ type: "boolean" \}/);
  assert.match(args, /"api-port": \{ type: "string" \}/);
  assert.match(configuredCommand, /runWebUiCommand/);
  assert.match(webCommand, /createWebSessionManager/);
  assert.match(webCommand, /resolveInitialWorkspace/);
  assert.match(webCommand, /march web \[workspace\]/);
  assert.match(webCommand, /only exposes local filesystem APIs/);
  assert.doesNotMatch(webCommand, /Choose a workspace/);
  assert.match(webCommand, /Web UI build not found/);
  assert.match(webCommand, /runWebUiDevCommand/);
  assert.match(webCommand, /createViteDevServer/);
  assert.match(webCommand, /proxy: \{ "\/api":/);
  assert.match(webCommand, /apiPort/);
  assert.match(sessionManager, /createWebRuntimeHost/);
  assert.match(sessionManager, /listFsRoots/);
  assert.match(sessionManager, /fsList/);
  assert.match(sessionManager, /activeSessionId/);
  assert.match(runtimeHost, /createRuntimeRunner/);
  assert.match(runtimeHost, /prepareTurnInput/);
  assert.match(runtimeHost, /runtimeUiEvents\.emit\(\{ type: "web_user_message"/);
  assert.match(runtimeHost, /type: "recall", hints:/);
  assert.match(server, /\/api\/snapshot/);
  assert.match(server, /\/api\/sessions/);
  assert.match(server, /\/api\/fs\/roots/);
  assert.match(server, /\/api\/fs\/list/);
  assert.match(server, /\/api\/provider-quota/);
  assert.match(server, /\/api\/events/);
  assert.match(server, /\/api\/turn/);
  assert.match(app, /useWebRuntime/);
  assert.match(shell, /<FileExplorer root=\{model\.workspace\}/);
  assert.match(shell, /<SessionTimeline timeline=\{model\.timeline\}/);
  assert.match(shell, /fsEntries=\{runtime\.fsEntries\}/);
  assert.match(shell, /providerQuota=\{model\.providerQuota\}/);
  assert.match(shell, /onCreateSession=\{runtime\.createSession\}/);
  assert.match(shell, /disabled=\{!model\.activeSessionId\}/);
  assert.match(model, /activeSessionId\?: string \| null/);
  assert.match(model, /workspacePath\?: string/);
  assert.match(model, /ProviderQuotaSnapshot/);
  assert.match(model, /MemoryRecallReport/);
  assert.match(model, /export type WebUiModel/);
  assert.match(model, /MarchTimelineEvent/);
  assert.match(model, /TimelineItem/);
  assert.match(model, /ActivityEvent/);
  assert.match(explorer, /@pierre\/trees\/react/);
  assert.match(explorer, /aria-label="Projects"/);
  assert.match(explorer, /className="projects-header"/);
  assert.match(explorer, /className="project-tree-host"/);
  assert.match(treeAdapter, /createProjectFileTreeInput/);
  assert.match(treeAdapter, /GitStatusEntry/);
  assert.match(timeline, /normalizeTimelineEvents/);
  assert.match(timeline, /runtime-pill/);
  assert.match(timeline, /<TimelineList items=\{items\}/);
  assert.match(timelineList, /aria-label="Session events"/);
  assert.match(timelineBlocks, /className="timeline-aux tool-block"/);
  assert.match(timelineBlocks, /MemoryRecallBlock/);
  assert.doesNotMatch(timelineBlocks, /permission-block/);
  assert.match(timelineAdapter, /tool_result/);
  assert.match(timelineAdapter, /memoryRecall/);
  assert.match(right, /Workspace picker/);
  assert.match(right, /onCreateSession/);
  assert.match(right, /onBrowsePath/);
  assert.match(right, /ProviderQuotaCard/);
  assert.match(right, /aria-label="Provider quota"/);
  assert.match(right, /className="right-header">会话/);
  assert.match(right, /right-divider">Activity/);
  assert.doesNotMatch(right, /todo|Todos/i);
  assert.match(composer, /disabled=\{disabled\}/);
  assert.match(composer, /onSubmit/);
  assert.match(composer, /value=\{prompt\}/);
  assert.match(runtimeClient, /new EventSource\(apiPath\("\/api\/events"/);
  assert.match(runtimeClient, /createRuntimeSession/);
  assert.match(runtimeClient, /fetchFsRoots/);
  assert.match(runtimeClient, /fetchProviderQuota/);
  assert.match(runtimeHook, /fetchRuntimeSnapshot/);
  assert.match(runtimeHook, /connectRuntimeEvents\(\s*activeSessionId/);
  assert.match(runtimeHook, /provider_quota_snapshot/);
  assert.match(runtimeHook, /rememberTimeline/);
  assert.match(runtimeHook, /restoreCachedTimeline/);
  assert.match(runtimeHook, /submitRuntimeTurn\(activeSessionId/);
  assert.match(runtimeTimeline, /applyRuntimeEvent/);
  assert.match(runtimeTimeline, /text_delta/);
  assert.match(runtimeTimeline, /memory_recall/);
  assert.match(css, /grid-template-areas: "sidebar main right" "sidebar footer right"/);
  assert.match(css, /height: var\(--header-height\)/);
  assert.match(css, /border-right: 1px solid var\(--color-border-subtle\)/);
  assert.match(css, /--trees-selected-bg-override: var\(--color-accent-soft\)/);
  assert.match(css, /\.timeline-aux/);
  assert.match(css, /\.runtime-pill\.connected/);
  assert.match(css, /\.workspace-picker/);
  assert.match(css, /\.provider-quota/);
  assert.match(css, /\.message-body[\s\S]*font-weight: var\(--font-weight-content-normal\)/);
  assert.match(css, /\.composer textarea[\s\S]*font-weight: var\(--font-weight-content-normal\)/);
  assert.match(css, /\.terminal-block pre/);
  assert.match(css, /\.memory-recall-block/);
  assert.match(css, /max-width: 920px/);
  assert.match(css, /data-left-open="true"/);
  assert.match(tokens, /@layer theme\.palette, theme\.semantic, theme\.component, base/);
  assert.match(tokens, /--palette-blue-600:/);
  assert.match(tokens, /--color-bg-surface:/);
  assert.match(tokens, /--shell-left-width:/);
  assert.doesNotMatch(tokens, /--bg:|--line:|--accent:/);
  assert.match(tokens, /--font-sans:/);
  assert.match(tokens, /--font-weight-ui-normal: 500/);
  assert.match(tokens, /--font-weight-content-normal: 600/);
  assert.match(tokens, /--font-weight-ui-medium: 600/);
  assert.match(tokens, /--font-weight-ui-strong: 700/);
  assert.match(tokens, /font-weight: var\(--font-weight-ui-normal\)/);
  assert.match(tokens, /"Segoe UI Variable Text"/);
  assert.match(tokens, /DengXian/);
  assert.match(tokens, /"等线"/);
  assert.match(tokens, /DengXian[\s\S]*"Microsoft YaHei UI"/);
  assert.doesNotMatch(tokens, /PingFang SC|Noto Sans CJK|Source Han Sans|微软雅黑/i);
  assert.doesNotMatch(css, /todo/i);
  assert.match(server, /text\/event-stream/);
  assert.equal(resolveStaticPath(root, "/..%2fpackage.json"), null);
  assert.ok(resolveStaticPath(root, "/")?.endsWith(join("web-ui", "index.html")));
  console.log("  PASS");
}
